POST http://localhost:3333/events 
Content-Type: application/json

{
    "title": "Novo Evento 2",
    "details": null,
    "maximumAttendees": 1
}

###

POST http://localhost:3333/events/4bf93e1c-a654-43f7-aa74-a104823f777f/attendees
Content-Type: application/json

{
    "name": "Igor Guerra",
    "email": "igor2@email.com"
}

###

GET http://localhost:3333/events/4bf93e1c-a654-43f7-aa74-a104823f777f


###

GET http://localhost:3333/attendees/2/badge


###

GET http://localhost:3333/attendees/3/check-in


###

GET http://localhost:3333/events/4bf93e1c-a654-43f7-aa74-a104823f777f/attendees